[env:esp32-2432s028r]
platform = espressif32 @ 6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43

build_flags =
  -DUSER_SETUP_LOADED
  -Iinclude
  -include include/User_Setup.h
